import { Inter } from "next/font/google";
import "./globals.css";
import homeCss from "./home.module.css";
const inter = Inter({ subsets: ["latin"] });
const routerArr = [
  {
    path: "/",
    name: "首页",
  },
  {
    path: "/about",
    name: "关于",
  },
];
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function BaseHeader() {
  return (
    <>
      <div className={homeCss.baseHeader}>
        <span>111</span>
        <span>222</span>
      </div>
    </>
  );
}
function LeftSide(routerData = []) {
  return (
    <>
      <div className={homeCss.leftSide}>
        <div>ddddd</div>
        <div>ddddd</div>
        <div>ddddd</div>
        <div>ddddd</div>
        <div>ddddd</div>
        <div>ddddd</div>
      </div>
    </>
  );
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          {BaseHeader()}
          <div className={homeCss.emptyHeader}></div>
          <div className={homeCss.Container}>
            {/* <span style={{ background: "blue", padding: "10px" }}>333</span> */}
            {/* <span style={{ background: "red", flex: 1 }}>222</span> */}

            <div>{LeftSide(routerArr)}</div>
            <div className={homeCss.mainContent}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
