import { Inter } from "next/font/google";
import "./globals.css";
import homeCss from "./home.module.css";
import Link from "next/link";
import BaseHeader from "@/components/home/Header";
const inter = Inter({ subsets: ["latin"] });
const routerArr = [
  {
    path: "/",
    name: "首页333333333333",
  },
  {
    path: "/about",
    name: "关于",
  },
];
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function LeftSide(routerData = []) {
  return (
    <>
      <div className={homeCss.leftSide}>
        {routerArr.map((item) => (
          <Link className={homeCss.Link} key={item.path} href={item.path}>
            {item.name}
          </Link>
        ))}
      </div>
    </>
  );
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <BaseHeader />
          <div className={homeCss.emptyHeader}></div>
          <div className={homeCss.Container}>
            {/* <span style={{ background: "blue", padding: "10px" }}>333</span> */}
            {/* <span style={{ background: "red", flex: 1 }}>222</span> */}

            <div>{LeftSide(routerArr)}</div>
            <div className={homeCss.mainContent}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
